import type { Promotion } from "./types.js";
import { promotionsArraySchema } from "./schemas.js";

export const promotions: Promotion[] = [
  {
    "id": "711-win-5-gratis-spins",
    "casino_slug": "711",
    "title": "Win €5 Gratis Spins",
    "type": "free_spins",
    "description": "Win €5 aan gratis spins op Temple Tumble van Relax Gaming.",
    "bonus_value": 5,
    "starts": "2026-03-23",
    "expires": "2026-03-29",
    "last_verified": "2026-03-28"
  },
  {
    "id": "711-15-000-greentube-toernooi",
    "casino_slug": "711",
    "title": "€15.000 Greentube Toernooi",
    "type": "tournament",
    "description": "Maak kans op de hoofdprijs van €1.500 in het Greentube toernooi met een prijzenpot van €15.000.",
    "bonus_value": 15000,
    "starts": "2026-03-26",
    "expires": "2026-03-30",
    "last_verified": "2026-03-28"
  },
  {
    "id": "711-10-000-multiplier-drops",
    "casino_slug": "711",
    "title": "10.000 Multiplier Drops",
    "type": "other",
    "description": "Win 10x tot 1000x je inzet met de Multiplier Drops actie.",
    "starts": "2026-03-03",
    "expires": "2026-03-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "711-20-stortingsbonus",
    "casino_slug": "711",
    "title": "20% Stortingsbonus",
    "type": "deposit_bonus",
    "description": "Ontvang 20% stortingsbonus op een storting naar keuze.",
    "bonus_value": 20,
    "starts": "2026-03-01",
    "expires": "2026-03-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betcity-win-250",
    "casino_slug": "betcity",
    "title": "Win €250",
    "type": "tournament",
    "description": "Maak dit weekend kans op €250 in het Casino!",
    "bonus_value": 250,
    "starts": "2026-03-28",
    "expires": "2026-03-29",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-betcity-paas-spinner",
    "casino_slug": "betcity",
    "title": "BetCity Paas Spinner",
    "type": "other",
    "description": "Maak iedere dag gratis kans op prachtige prijzen met de Paas Spinner!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-20-free-spins-energy-coins",
    "casino_slug": "betcity",
    "title": "20 Free Spins - Energy Coins",
    "type": "free_spins",
    "description": "Stort en pak 20 Free Spins voor Energy Coins: Hold and Win!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-5-gift-card-lightning-roulette",
    "casino_slug": "betcity",
    "title": "€5 Gift Card Lightning Roulette",
    "type": "other",
    "description": "Claim een €5 Gift Card voor BetCity NL Lightning Roulette!",
    "bonus_value": 5,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-25-free-spins-thunder-coins-xxl",
    "casino_slug": "betcity",
    "title": "25 Free Spins - Thunder Coins XXL",
    "type": "free_spins",
    "description": "Stort en pak 25 Free Spins voor Thunder Coins XXL: Multicoin!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-5-gift-card-dutch-roulette",
    "casino_slug": "betcity",
    "title": "€5 Gift Card Dutch Roulette",
    "type": "other",
    "description": "Stort en claim een €5 Gift Card voor BetCity Dutch Roulette!",
    "bonus_value": 5,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-50-free-spins-wekelijks",
    "casino_slug": "betcity",
    "title": "50 Free Spins Wekelijks",
    "type": "free_spins",
    "description": "Speel iedere week 50 Free Spins vrij in het Casino!",
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-5-aan-gift-cards-wekelijks",
    "casino_slug": "betcity",
    "title": "€5 aan Gift Cards Wekelijks",
    "type": "other",
    "description": "Claim elke week tot €5 aan Gift Cards in het Live Casino!",
    "bonus_value": 5,
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-pirots-toernooi",
    "casino_slug": "betcity",
    "title": "Pirots Toernooi",
    "type": "tournament",
    "description": "Speel mee in het Casino en maak kans op €1.500!",
    "bonus_value": 1500,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-gameshow-toernooi",
    "casino_slug": "betcity",
    "title": "Gameshow Toernooi",
    "type": "tournament",
    "description": "Ga voor de hoofdprijs van €1.000 in het Live Casino!",
    "bonus_value": 1000,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-azen-zijn-bazen",
    "casino_slug": "betcity",
    "title": "Azen zijn Bazen",
    "type": "other",
    "description": "Heb je 2 azen in je hand? Dan pak je een €10 Gift Card!",
    "bonus_value": 10,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-straight-ups",
    "casino_slug": "betcity",
    "title": "Straight Ups",
    "type": "other",
    "description": "Win extra als het balletje 5 keer op jouw getal valt!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-gameshow-bonus",
    "casino_slug": "betcity",
    "title": "Gameshow Bonus",
    "type": "free_spins",
    "description": "Ontdek gratis de vetste Gameshows van Evolution!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-mines-20-free-rounds",
    "casino_slug": "betcity",
    "title": "Mines: 20 Free Rounds",
    "type": "free_spins",
    "description": "Ontvang 20 gratis speelronden voor Mines van Hacksaw!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-wekelijkse-bonus",
    "casino_slug": "betcity",
    "title": "Wekelijkse Bonus",
    "type": "other",
    "description": "Speel iedere week bij BetCity en ontvang wekelijks een of meerdere bonussen!",
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-royaal-toernooi",
    "casino_slug": "betcity",
    "title": "Royaal Toernooi",
    "type": "tournament",
    "description": "Maak kans op de hoofdprijs van €2.000 in het Casino!",
    "bonus_value": 2000,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betcity-20-free-spins-nieuwsbrief",
    "casino_slug": "betcity",
    "title": "20 Free Spins Nieuwsbrief",
    "type": "free_spins",
    "description": "Abonneer op de nieuwsbrief en krijg 20 Free Spins!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "betnation-games-global-toernooi",
    "casino_slug": "betnation",
    "title": "Games Global Toernooi",
    "type": "tournament",
    "description": "Doe mee aan het wekelijkse toernooi bij Games Global en maak kans op een deel van de prijzenpot van €1000.",
    "bonus_value": 1000,
    "starts": "2026-03-23",
    "expires": "2026-03-29",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betnation-gates-of-olympus-super-scatter-gratis-spins",
    "casino_slug": "betnation",
    "title": "Gates Of Olympus Super Scatter Gratis Spins",
    "type": "free_spins",
    "description": "Stort vanaf €50 en ontvang tot 50 gratis spins bij Gates Of Olympus Super Scatter.",
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betnation-dagelijkse-mystery-spins",
    "casino_slug": "betnation",
    "title": "Dagelijkse Mystery Spins",
    "type": "free_spins",
    "description": "Voltooi de dagelijkse Mystery Spins bij Betnation en ontvang tussen de 5 en 100 gratis spins. Hoeveel je krijgt blijft een verrassing!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betnation-nieuwsbrief-gratis-spins",
    "casino_slug": "betnation",
    "title": "Nieuwsbrief Gratis Spins",
    "type": "free_spins",
    "description": "Schrijf je in voor de nieuwsbrief en ontvang maandelijks tot wel 50 gratis spins voor de leukste spellen.",
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betnation-drops-wins-pragmatic-play",
    "casino_slug": "betnation",
    "title": "Drops & Wins Pragmatic Play",
    "type": "tournament",
    "description": "Doe mee met de Drops & Wins bij geselecteerde Pragmatic Play-spellen en maak kans op dagelijkse prize drops.",
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betnation-voetbal-free-bet-interland-break",
    "casino_slug": "betnation",
    "title": "Voetbal Free Bet Interland Break",
    "type": "other",
    "description": "Zet €20 in op voetbal tijdens de interland break en ontvang een €5 Free Bet (live in te zetten).",
    "bonus_value": 5,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "betnation-25-bet-builder-profit-boosts",
    "casino_slug": "betnation",
    "title": "25% Bet Builder Profit Boosts",
    "type": "other",
    "description": "Pak tot maar liefst €1.000 extra met 25% Bet Builder Profit Boosts op jouw favoriete wedstrijden.",
    "bonus_value": 1000,
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "casino777-aanbieder-van-de-maand-pragmatic-play",
    "casino_slug": "casino777",
    "title": "Aanbieder van de Maand - Pragmatic Play",
    "type": "free_spins",
    "description": "Zet €50 in op Gates of Olympus Super Scatter en ontvang 10 wekelijkse Gratis Spins. Geldig van 2 maart t/m 29 maart. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 1,
    "wagering_multiplier": 0,
    "starts": "2026-03-02",
    "expires": "2026-03-29",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-gok-50-en-ontvang-10-gratis-spins",
    "casino_slug": "casino777",
    "title": "Gok €50 en ontvang 10 Gratis Spins",
    "type": "free_spins",
    "description": "Zet €50 in op Coin Strike XXL: hold and win en ontvang 10 Gratis Spins. Eenmalige deelname van 24 t/m 29 maart. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 1,
    "wagering_multiplier": 0,
    "starts": "2026-03-24",
    "expires": "2026-03-29",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-stakelogic-gok-100-en-ontvang-25-gratis-spins",
    "casino_slug": "casino777",
    "title": "Stakelogic Gok €100 en ontvang 25 Gratis Spins",
    "type": "free_spins",
    "description": "Zet €100 in op Big Runner Deluxe of Gold Winner Jackpot en ontvang 25 Gratis Spins. Eenmalige deelname van 25 t/m 29 maart. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 2.5,
    "wagering_multiplier": 0,
    "starts": "2026-03-25",
    "expires": "2026-03-29",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-gok-75-en-ontvang-15-gratis-spins",
    "casino_slug": "casino777",
    "title": "Gok €75 en ontvang 15 Gratis Spins",
    "type": "free_spins",
    "description": "Zet €75 in op Mahjong Magic, Baa Baa Baa of The Raccaroon en ontvang 15 Gratis Spins per dag. Geldig van 26 t/m 29 maart. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 1.5,
    "wagering_multiplier": 0,
    "starts": "2026-03-26",
    "expires": "2026-03-29",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-hacksaw-wekelijks-bet-en-get-amazing-miceketeers",
    "casino_slug": "casino777",
    "title": "Hacksaw Wekelijks Bet en Get: Amazing Miceketeers",
    "type": "free_spins",
    "description": "Zet €100 in op Amazing Miceketeers en ontvang 25 wekelijkse Gratis Spins op geselecteerde Red Tiger games. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 2.5,
    "wagering_multiplier": 0,
    "starts": "2026-03-06",
    "expires": "2026-03-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-rad-van-fortuin-777",
    "casino_slug": "casino777",
    "title": "Rad van Fortuin 777",
    "type": "free_spins",
    "description": "Draai dagelijks gratis aan het rad en claim je prijzen. Na aanmelding en een storting van minimaal €10 in de afgelopen 7 dagen kun je elke dag gratis spins winnen op geselecteerde Red Tiger spellen.",
    "wagering_multiplier": 0,
    "starts": "2026-03-27",
    "expires": "2026-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-speel-gridders-spellen-en-ontvang-gratis-spins",
    "casino_slug": "casino777",
    "title": "Speel Gridders-spellen en ontvang gratis spins",
    "type": "free_spins",
    "description": "Zet minimaal €50 in op Gridders-spellen en claim dagelijks 10 gratis spins op geselecteerde Red Tiger spellen. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 1,
    "wagering_multiplier": 0,
    "starts": "2026-01-01",
    "expires": "2026-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "casino777-speel-live-casino-in-2026-en-ontvang-freespins",
    "casino_slug": "casino777",
    "title": "Speel live casino in 2026 en ontvang freespins",
    "type": "free_spins",
    "description": "Zet minimaal €100 in op geselecteerde live casinospellen en ontvang dagelijks 25 freespins op Red Tiger spellen. Spinwaarde €0,10, 0x doorspeel vereiste.",
    "bonus_value": 2.5,
    "wagering_multiplier": 0,
    "starts": "2026-01-01",
    "expires": "2026-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "circus-pragmatic-play-toernooi",
    "casino_slug": "circus",
    "title": "Pragmatic Play Toernooi",
    "type": "tournament",
    "description": "Pak jouw kans op een deel van €2.000 in het Pragmatic Play-toernooi van 27 maart t/m 2 april.",
    "bonus_value": 2000,
    "starts": "2026-03-27",
    "expires": "2026-04-02",
    "last_verified": "2026-03-27"
  },
  {
    "id": "circus-scoor-100-free-spins-free-spin-mania",
    "casino_slug": "circus",
    "title": "Scoor 100 Free Spins! – Free Spin Mania",
    "type": "free_spins",
    "description": "Free Spin Mania is begonnen! Ontvang tot 100 Free Spins en ontdek nog meer speelplezier.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "fair-play-online-drops-wins",
    "casino_slug": "fair-play-online",
    "title": "Drops & Wins",
    "type": "tournament",
    "description": "Ontdek de Drops & Wins van Pragmatic Play: speel geselecteerde slots en live casinospellen en maak kans op dagelijkse en wekelijkse prijzen.",
    "starts": "2025-03-05",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "fair-play-online-fair-play-drops-mighty-odin",
    "casino_slug": "fair-play-online",
    "title": "Fair Play Drops - Mighty Odin",
    "type": "other",
    "description": "Speel de slot Mighty Odin van Spinomenal bij Fair Play Casino en maak kans op 1000 keer je inzet met de Fair Play Drops.",
    "starts": "2026-01-01",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-games-global-toernooi",
    "casino_slug": "jacks-nl",
    "title": "Games Global Toernooi",
    "type": "tournament",
    "description": "Casino toernooi met een prijzenpot van €5.000 bij Games Global slots.",
    "bonus_value": 5000,
    "starts": "2026-03-26",
    "expires": "2026-03-30",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-pragmatic-play-prijs-drop",
    "casino_slug": "jacks-nl",
    "title": "Pragmatic Play Prijs Drop",
    "type": "tournament",
    "description": "Prijzendrop actie bij Pragmatic Play slots met willekeurige prijzen.",
    "starts": "2026-03-04",
    "expires": "2026-04-01",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-wekelijks-kans-op-100-aan-free-spins",
    "casino_slug": "jacks-nl",
    "title": "Wekelijks Kans op €100 aan Free Spins",
    "type": "free_spins",
    "description": "Doe wekelijks gratis mee en maak kans op €100 aan free spins in het casino.",
    "bonus_value": 100,
    "starts": "2026-03-18",
    "expires": "2026-06-10",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-grand-slam-wimbledon-1-000-prijzengeld",
    "casino_slug": "jacks-nl",
    "title": "Grand Slam Wimbledon: €1.000 Prijzengeld",
    "type": "tournament",
    "description": "Win tot €1.000 aan prijzengeld tijdens het Wimbledon tennistoernooi.",
    "bonus_value": 1000,
    "starts": "2026-06-30",
    "expires": "2026-07-13",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-wk-voor-clubs-4x-10-free-bets",
    "casino_slug": "jacks-nl",
    "title": "WK voor Clubs: 4x €10 Free Bets",
    "type": "free_spins",
    "description": "Scoor 4 keer €10 aan free bets tijdens het WK voor clubs.",
    "bonus_value": 40,
    "starts": "2026-06-14",
    "expires": "2026-07-13",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-winnaars-adventskalender",
    "casino_slug": "jacks-nl",
    "title": "Winnaars Adventskalender",
    "type": "other",
    "description": "Langlopende adventskalender-actie voor casino en sport met dagelijkse prijzen.",
    "starts": "2026-01-01",
    "expires": "2026-10-07",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-octoplay-jackspot-hunt",
    "casino_slug": "jacks-nl",
    "title": "Octoplay: Jackspot Hunt",
    "type": "tournament",
    "description": "Jackpot hunt actie bij Octoplay casino slots. Einddatum nog te bevestigen.",
    "starts": "2026-02-02",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-nodig-vrienden-uit-bonus",
    "casino_slug": "jacks-nl",
    "title": "Nodig Vrienden Uit Bonus",
    "type": "deposit_bonus",
    "description": "Nodig vrienden uit en ontvang tot €300 bonus. Vernieuwde refer-a-friend actie.",
    "bonus_value": 300,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-kraker-van-eigen-bodem-1-free-bet",
    "casino_slug": "jacks-nl",
    "title": "Kraker van Eigen Bodem: €1 Free Bet",
    "type": "free_spins",
    "description": "Claim wekelijks een €1 free bet op Nederlandse sportwedstrijden.",
    "bonus_value": 1,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-premier-league-darts-5-free-bet",
    "casino_slug": "jacks-nl",
    "title": "Premier League Darts: €5 Free Bet",
    "type": "free_spins",
    "description": "Pak elke week een €5 free bet op de Premier League Darts.",
    "bonus_value": 5,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-eredivisie-kkd-25-free-bet",
    "casino_slug": "jacks-nl",
    "title": "Eredivisie & KKD: €25 Free Bet",
    "type": "free_spins",
    "description": "Scoor wekelijks een €25 free bet op Eredivisie en Keuken Kampioen Divisie wedstrijden.",
    "bonus_value": 25,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-wedstrijd-van-de-week-5-free-bet",
    "casino_slug": "jacks-nl",
    "title": "Wedstrijd van de Week: €5 Free Bet",
    "type": "free_spins",
    "description": "Scoor wekelijks een €5 free bet op de wedstrijd van de week.",
    "bonus_value": 5,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-de-jacks-nl-kantine-assistjes",
    "casino_slug": "jacks-nl",
    "title": "De JACKS.NL Kantine: Assistjes",
    "type": "other",
    "description": "Wekelijkse sports actie waarbij je kunt scoren met assistjes bij JACKS.NL.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-premier-league-profit-boost-20-extra-winst",
    "casino_slug": "jacks-nl",
    "title": "Premier League Profit Boost: 20% Extra Winst",
    "type": "other",
    "description": "Scoor wekelijks 20% extra winst op Premier League weddenschappen met een profit boost.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-nba-5-free-bet",
    "casino_slug": "jacks-nl",
    "title": "NBA: €5 Free Bet",
    "type": "free_spins",
    "description": "Pak wekelijks een €5 free bet op NBA basketbalwedstrijden.",
    "bonus_value": 5,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-formule-1-10-free-bet",
    "casino_slug": "jacks-nl",
    "title": "Formule 1: €10 Free Bet",
    "type": "free_spins",
    "description": "Pak elke raceweek een €10 free bet op Formule 1 wedstrijden.",
    "bonus_value": 10,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-quiz-win-tot-25-000",
    "casino_slug": "jacks-nl",
    "title": "Quiz: Win tot €25.000",
    "type": "other",
    "description": "Doe dagelijks je voorspelling en maak kans op prijzen tot €25.000.",
    "bonus_value": 25000,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "jacks-nl-jack-s-challenges",
    "casino_slug": "jacks-nl",
    "title": "Jack's Challenges",
    "type": "other",
    "description": "Wekelijkse sports challenges waarbij je de uitdaging aangaat voor prijzen.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-elke-maand-85-free-spins",
    "casino_slug": "leovegas",
    "title": "Elke Maand 85 Free Spins",
    "type": "free_spins",
    "description": "Met het Free Spin Festival pak je een jaar lang in totaal ruim 1000 Free Spins op Henry the Ape! Speel iedere maand mee.",
    "bonus_value": 85,
    "starts": "2026-03-01",
    "expires": "2026-03-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-leojackpot",
    "casino_slug": "leovegas",
    "title": "LeoJackpot",
    "type": "other",
    "description": "De LeoJackpot blijft maar oplopen en met vier progressieve jackpots maak je nog meer kans!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-leovegas-haaienpakket",
    "casino_slug": "leovegas",
    "title": "LeoVegas Haaienpakket",
    "type": "free_spins",
    "description": "Kies elke donderdag jouw Haaienpakket in het casino en speel gratis op vintastische slots!",
    "starts": "2026-03-26",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-leo-s-golden-gates-pakket",
    "casino_slug": "leovegas",
    "title": "Leo's Golden Gates Pakket",
    "type": "free_spins",
    "description": "Met de Golden Gates pakketten pak je elke dinsdag tot wel 120 Free Spins voor Gates of LeoVegas 1000.",
    "bonus_value": 120,
    "starts": "2026-03-31",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-live-casino-classics",
    "casino_slug": "leovegas",
    "title": "Live Casino Classics",
    "type": "other",
    "description": "Stap terug in de tijd met LeoVegas Live Casino Classics. Pak elke week tot wel €35 aan gratis Reward Games.",
    "bonus_value": 35,
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-acca-profit-boost",
    "casino_slug": "leovegas",
    "title": "Acca Profit Boost",
    "type": "deposit_bonus",
    "description": "Verhoog je winsten met een Profit Boost! Combineer weddenschappen en scoor tot wel 50% extra, elke week!",
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-wekelijkse-10-free-bet",
    "casino_slug": "leovegas",
    "title": "Wekelijkse €10 Free Bet",
    "type": "other",
    "description": "Pak wekelijks een Free Bet met LeoVegas Extra! Plaats een voetbal Acca én Bet Builder en scoor een €10 Live Free Bet.",
    "bonus_value": 10,
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "leovegas-100-profit-boost",
    "casino_slug": "leovegas",
    "title": "100% Profit Boost",
    "type": "deposit_bonus",
    "description": "Boost je Bet Builder weddenschappen en pak wekelijks een 100% Profit Boost tot €1000. Speel nu bij LeoVegas!",
    "bonus_value": 1000,
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "toto-speel-crazy-time-en-maak-kans-op-een-deel-van-10-000",
    "casino_slug": "toto",
    "title": "Speel Crazy Time en maak kans op een deel van €10.000",
    "type": "tournament",
    "description": "Neem deel aan alle 4 de bonusspellen van Crazy Time en win een mooie geldprijs uit een prijzenpot van €10.000.",
    "bonus_value": 10000,
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-lucky-number-7-bij-toto-lightning-roulette",
    "casino_slug": "toto",
    "title": "Lucky Number 7 bij TOTO Lightning Roulette",
    "type": "tournament",
    "description": "Speel TOTO Lightning Roulette en maak kans op een deel van €10.000.",
    "bonus_value": 10000,
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-verdien-gratis-chips-voor-toto-lightning-roulette",
    "casino_slug": "toto",
    "title": "Verdien Gratis Chips voor TOTO Lightning Roulette",
    "type": "other",
    "description": "Speel TOTO Lightning Roulette en verdien €5 Gratis Chips.",
    "bonus_value": 5,
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-game-show-specials",
    "casino_slug": "toto",
    "title": "Game Show Specials",
    "type": "tournament",
    "description": "Elke week een nieuwe actie! Speel mee en maak kans op een deel van €10.000.",
    "bonus_value": 10000,
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-toto-lucky-777",
    "casino_slug": "toto",
    "title": "TOTO Lucky 777",
    "type": "free_spins",
    "description": "Maak kans op €100 Gratis Chips aan de Live TOTO Blackjack tafels.",
    "bonus_value": 100,
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-koning-toto-bij-blackjack",
    "casino_slug": "toto",
    "title": "Koning TOTO bij Blackjack!",
    "type": "cashback",
    "description": "Maak kans op €100 extra cash aan de Live Blackjack tafels.",
    "bonus_value": 100,
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-drops-wins-van-pragmatic-play",
    "casino_slug": "toto",
    "title": "Drops & Wins van Pragmatic Play!",
    "type": "tournament",
    "description": "Maak elke dag kans op extra prijzen op Pragmatic Play slotmachines.",
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-toto-toernooien-kans-op-cash-of-gratis-spins",
    "casino_slug": "toto",
    "title": "TOTO toernooien: kans op cash of Gratis Spins",
    "type": "tournament",
    "description": "Maak elke week en elk weekend kans op cash of Gratis Spins met een toernooi in het TOTO Casino.",
    "starts": "2026-03-23",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-toto-maandag",
    "casino_slug": "toto",
    "title": "TOTO Maandag!",
    "type": "free_spins",
    "description": "Ontvang 5 Gratis Spins en maak kans op Cash of Extra Spins elke maandag.",
    "starts": "2026-03-30",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "toto-toto-exclusief",
    "casino_slug": "toto",
    "title": "TOTO Exclusief",
    "type": "free_spins",
    "description": "Verdien Gratis Spins met een spel dat je exclusief bij TOTO speelt.",
    "starts": "2026-03-28",
    "expires": "2099-12-31",
    "last_verified": "2026-03-28"
  },
  {
    "id": "unibet-50-000-pot-o-prizes",
    "casino_slug": "unibet",
    "title": "€50.000 Pot O Prizes",
    "type": "tournament",
    "description": "Gooi je hengel uit en maak kans op een deel van €50.000! In-game aanmelden vereist, min. spin inzet €0,10.",
    "bonus_value": 50000,
    "starts": "2026-03-02",
    "expires": "2026-03-29",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-casino-toernooi-festival",
    "casino_slug": "unibet",
    "title": "Casino Toernooi Festival",
    "type": "tournament",
    "description": "Een aaneenschakeling van toernooien met slots en live tafels, telkens met een prijzenpot van €5.000 cash. Inschrijven vereist, min. inzet €0,10.",
    "bonus_value": 5000,
    "starts": "2026-02-02",
    "expires": "2026-03-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-wekelijkse-grind-missie",
    "casino_slug": "unibet",
    "title": "Wekelijkse Grind Missie",
    "type": "tournament",
    "description": "Voltooi elke week een missie om je ticket te verdienen voor het Weekly Grind Special Toernooi. Inschrijven vereist.",
    "starts": "2026-02-09",
    "expires": "2026-04-05",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-banzai-bonanza-elke-vrijdag",
    "casino_slug": "unibet",
    "title": "Banzai Bonanza elke vrijdag",
    "type": "tournament",
    "description": "Elke vrijdagavond een speciale €50 buy-in Banzai pokertoernooi. Inschrijven vereist, min. buy-in €1.",
    "starts": "2023-10-01",
    "expires": "2026-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-combo-booster",
    "casino_slug": "unibet",
    "title": "Combo Booster",
    "type": "other",
    "description": "Tot 50% extra cash op je combinatieweddenschap. Hoe groter je combinaties, hoe meer ze geboost worden (4% tot 50%). Onbeperkt aanbod, geldig op alle sporten.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-uniboosts",
    "casino_slug": "unibet",
    "title": "Uniboosts",
    "type": "other",
    "description": "Verhoog je odds tijdelijk op geselecteerde (voetbal)weddenschappen. Alleen zichtbaar na inloggen.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-5-000-aan-prijzen-elk-weekend",
    "casino_slug": "unibet",
    "title": "€5.000 aan prijzen, elk weekend",
    "type": "tournament",
    "description": "Neem elk weekend plaats aan Pragmatic Play LIVE tafels en maak kans op willekeurige cash prijzen. Min. inzet €1, inschrijven vereist.",
    "bonus_value": 5000,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-de-penny-bingo-room",
    "casino_slug": "unibet",
    "title": "De Penny Bingo Room",
    "type": "other",
    "description": "Betaalbaar bingo-plezier met kaartjes vanaf €0,01. Max 25 kaartjes per speler per dag, eerlijke kansen. Dagelijks van 09:05 tot 00:00 CET.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-unibet-open-2026",
    "casino_slug": "unibet",
    "title": "Unibet Open 2026",
    "type": "tournament",
    "description": "The Unibet Open keert terug in 2026 met de aftrap in Parijs. Algemene voorwaarden van toepassing.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-the-festival-series",
    "casino_slug": "unibet",
    "title": "The Festival Series",
    "type": "tournament",
    "description": "Win pakketten ter waarde van €1.500 voor pokertoernooien in Bratislava, Rozvadov, Malta en Riga.",
    "bonus_value": 1500,
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-unibet-deep-stack-open",
    "casino_slug": "unibet",
    "title": "Unibet Deep Stack Open",
    "type": "tournament",
    "description": "De UDSO stuurt je naar de mooiste pokertoernooien in Europa. Doe mee en win!",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  },
  {
    "id": "unibet-hot-drops",
    "casino_slug": "unibet",
    "title": "Hot Drops",
    "type": "other",
    "description": "Activeer de Hot Drops Jackpot en speel automatisch mee voor vier progressieve jackpots op honderden favoriete slots. Na uitloggen stopt deelname.",
    "starts": "2026-03-27",
    "expires": "2099-12-31",
    "last_verified": "2026-03-27"
  }
];

promotionsArraySchema.parse(promotions);
